### ISSUE TITLE
Add support for modifying the run history cleanup check interval

### ISSUE THREAD

**Issue by Froosh** [lithnet/miis-autosync#100]
Question and/or enhancement request

**Comment by ryannewington** [comment]
It will check every 8 hours for run history items older than what was configured in the settings page in the UI

**Comment by ryannewington** [comment]
In the next release, you can create a dword value for `RunHistoryTimerInterval` which indicates the number of minutes to run the run history cleanup. By default this value is not present and defaults to 8 hours.

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\autosync\Parameters
```

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.1.6500
