### ISSUE TITLE
Bug, installer won't continue, user is already member of group. 

### ISSUE THREAD

**Issue by Identitry** [lithnet/miis-autosync#104]
Hi!
Just tried installing Auto Sync for the first time but unfortunately the installer stops at this page.
The user is already a member of the group but when trying to continue with the OK button the dialog just pops up again. Currently I don't have write access to the group and can't try letting the installer add the user.

The user is a user account made for running Scheduled Tasks and have "Log On as Batch" permissions.
The group is the default Sync Admins group.

![image](https://user-images.githubusercontent.com/5760253/30859927-ce1bc3c4-a2c5-11e7-9f33-60710183ac23.png)

**Comment by ryannewington** [comment]
Can you rerun the installer from the command line to get verbose logs

Msiexec /i autosync.log /l*vx install.log

You can email me the log file ryan@lithnet.io

**Comment by ryannewington** [comment]
Could it be related to this issue?

```
“System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(…)” you need to assign “read” rights for both “CN=Users” and “CN=Computers” default AD containers for the application account.
```

http://blogs.msdn.com/b/dsadsi/archive/2009/08/28/getting-an-exception-the-specified-directory-service-attribute-or-value-does-not-exist-when-you-try-to-search-a-user-in-an-ad-container-using-system-directoryservices-accountmanagement-userprincipal-findbyidentity.aspx

**Comment by ryannewington** [comment]
And it would be referring to the account you are running the installer as. Not the service account.

**Comment by Identitry** [comment]
Hi!
It could be the problem, the solution I’m working on is in a small part of a common hosting AD it looks like I don’t have access to the default OU’s.
Guess I have to find another way of installing it unless you have a solution or work around?

//Henrik

**Comment by ryannewington** [comment]
I'll find a way around it for you.

**Comment by ryannewington** [comment]
@Identitry using the build in #102, execute the following command line to work around the issue for now

```
msiexec /i autosync.msi SKIPGROUPCHECK=1
```

**Comment by alfgil** [comment]
FYI: I ran into the same problem, in our test-lab system, and the solution above worked fine. When setting it up in production, the errormessage was slightly different, and the solution above did not help me out. 
![capture](https://user-images.githubusercontent.com/32637207/31335099-67bfd328-acf1-11e7-8119-c93566055d96.PNG). Here it turned out I had an orphan SID as Group member. After deleting this, validation of the new user worked fine and I am ready to play.

**Comment by ryannewington** [comment]
Hi @alfgil 

The issue you mentioned there is fixed in this issue https://github.com/lithnet/miis-autosync/issues/103

The build containing these fixes will be released next week

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.1.6500
