### ISSUE TITLE
Trigger log messages appear multiple times after stopping and starting a controller

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/miis-autosync#110]
Running v1.0.6471, I can see that AD/LDS change detection is detection the same object multiple times immediately (4 times to be exact), and then adding an exection queue.. 

Is this expected to see 4 times within the same second? Log writing bug or something else?

**Comment by ryannewington** [comment]
6471 is the initial release build from 2 weeks ago. Are you are you are talking about that version?

**Comment by ryannewington** [comment]
Are you saying that 4 DIs got added to the execution queue, or there were 4 ad changes detected for the same object?

**Comment by khandelwalpiyush** [comment]
Yes, as mentioned above.. and that is the official public release so wanted to confirm the findings

**Comment by khandelwalpiyush** [comment]
4 AD changes detected for same object at same timestamp ..

Well, now its increased to 5.. so some cyclic counter is adding on.. which might be happening after stopping and starting autosync from GUI

Confirmed Bug: Stop and start autosync from GUI and now its increased to 6

> 10/10/2017 8:59:15 AM: LDS: AD/LDS change detection (fimlds): Starting AD/LDS change detection (fimlds)
> 10/10/2017 8:59:15 AM: LDS: AD/LDS change detection (fimlds): Starting AD/LDS change detection (fimlds)
> 10/10/2017 8:59:15 AM: LDS: AD/LDS change detection (fimlds): Starting AD/LDS change detection (fimlds)
> 10/10/2017 8:59:15 AM: LDS: AD/LDS change detection (fimlds): Starting AD/LDS change detection (fimlds)
> 10/10/2017 8:59:15 AM: LDS: AD/LDS change detection (fimlds): Starting AD/LDS change detection (fimlds)
> 10/10/2017 8:59:15 AM: LDS: AD/LDS change detection (fimlds): Starting AD/LDS change detection (fimlds)

For both LDS and AD detection - same results

**Comment by ryannewington** [comment]
Ok thats odd. To be clear, its not detecting multiple changes, its spinning up multiple instances of the trigger

**Comment by ryannewington** [comment]
It is a cosmetic logging issue. The log message listener was not being removed when stopping the controller, but a new one was added when starting the controller. Actually impacted all trigger types.

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.1.6500
