### ISSUE TITLE
Cannot determine FIM admin groups from sync engine when SQL server database is installed remotely

### ISSUE THREAD

**Issue by dminnelli** [lithnet/miis-autosync#112]
Hi Ryan,

  I'm facing an installer issue which I can't seem to bypass. I checked issues #103 and #104 but my issue seems to be different. The same message appears if the service account is manually added to the group or not. I'll email you the msiexec installation log.

  Cheers

  Dave
![autosync_issue](https://user-images.githubusercontent.com/19176623/31590917-bb3adb2e-b264-11e7-8d8a-a523263eb208.png)

**Comment by ryannewington** [comment]
Hi @dminnelli,

Use the latest build found at the end of #102  which will allow you to use the SKIPGROUPCHECK parameter in #104 

Still send me the log and i'll investigate the issue, but this should allow you to proceed.

Ryan

**Comment by dminnelli** [comment]
Thanks @ryannewington. That version of the software has worked when using the SKIPGROUPCHECK parameter. Cheers. Dave

**Comment by ryannewington** [comment]
[autosync.zip](https://github.com/lithnet/miis-autosync/files/1389341/autosync.zip)

@dminnelli here is an updated build that fixes this and #113 if you need the fixes or would like to test them

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.1.6500
