### ISSUE TITLE
AutoSync incorrectly assumes PowerShell 5 is installed

### ISSUE THREAD

**Issue by dminnelli** [lithnet/miis-autosync#113]
Hi @ryannewington,

  I have received the following error in setting up a PowerShell trigger - '_The PowerShell execution trigger encountered an error and has been terminated_'

![autosync_issue1](https://user-images.githubusercontent.com/19176623/31609286-36f7a0d0-b2bf-11e7-8008-ced3bc4d1a20.png)

  My sample script for my test was simply:

_function Get-RunProfileToExecute
{
  write-output "FI";
}_

  You suggested checking the PowerShell version I was using. The AutoSync tool pre-requisites suggest PowerShell 3.0 or later. My server was using PowerShell 4.0 running on Windows Server 2012 R2. This was the output:

**$PSVersionTable.PSVersion**
_Major  Minor  Build  Revision
4      0      -1     -1_

**$PSVersionTable**
_Name                           Value
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18773
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2_

  Upgrading to PowerShell 5.0 by installing Windows Management Framework 5.0 has done the trick and my PowerShell script is working as required.
  Any clue on why it didn't work with PowerShell 4.0?

  Regards

  Dave

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.1.6500
