### ISSUE TITLE
Add support for providing credentials to the PowerShell trigger

### ISSUE THREAD

**Issue by Identitry** [lithnet/miis-autosync#114]
Finally I've been able to set it up for a customer however not for the multi-partition support thought. So far it looks great however...

I would love to be able to pass in a credential into the Powershell trigger script for contacting a web service or whatever source I've got. I can of course store the credential object on disk using Export-CliXml however It would be nice to have all configuration stored in one place.

Edit: If there also would be a way of passing in a last import datetime value it would be easy to find out if there are any changes available in the connected system that could be a web service, database or what ever as long as the source allows it...

**Comment by ryannewington** [comment]
@Identitry I will look to add this functionality in. The credentials inside the service are encrypted so we can take advantage of this mechanism.

Regarding the last import time, use the pattern I use in my trigger script for ACMA to do what you are describing. The PS session remains in place at all times, so you can use global variables to store things like watermarks in between calls to Get-RunProfileToExecute

https://github.com/lithnet/miis-autosync/blob/master/src/Lithnet.Miiserver.AutoSync/Examples/Trigger-ACMA-CheckPendingImports.ps1

**Comment by ryannewington** [comment]
@Identitry sorry for the delay on this one. I've got a build ready to test here if you are still interested in this functionality.

[autosync.zip](https://github.com/lithnet/miis-autosync/files/1610436/autosync.zip)

Just provide the credentials in the UI and update your PowerShell function definition to

```powershell
function Get-RunProfileToExecute($credentials) 
{
...
}
```

Let me know how you go

**Comment by ryannewington** [comment]
Done in https://github.com/lithnet/miis-autosync/releases/tag/v1.2.6692
