### ISSUE TITLE
Ability to add list of attributes to ignore for AD/LDS Change detection

### ISSUE THREAD

**Issue by hansdavid** [lithnet/miis-autosync#118]
I get too many empty imports on the AD-MA, and would like to specify in more detail what **not** to trigger on, alternatively what **to** trigger on

**Comment by ryannewington** [comment]
@hansdavid Unfortunately, the change detection mechanism offered by AD only tells that an object changed, it doesn't tell us what attributes specifically were modified.

However, I've seen a few cases where a rogue process in AD was performing excessive and unnecessary modifications of an AD object, resulting in an import every 60 seconds (the default interval on the trigger). 

The autosync.log file will show you what object changed, and sometimes that can help track it down if you can see lots of repeated entries for the same object. Have a look and see if it explains the behaviour you are seeing. Let me know what you find.

Ryan

**Comment by hansdavid** [comment]
Yes, I am experiencing these excessive modifications on certain objects.
I will try to trace these, and let you know.
is the detection mechanism based on USN (Update Sequence Numbers)?
//hd

**Comment by ryannewington** [comment]
@hansdavid it uses an asynchronous persistent search using the LDAP_SERVER_NOTIFICATION control
https://msdn.microsoft.com/en-us/library/aa772153(v=vs.85).aspx

**Comment by ryannewington** [comment]
@hansdavid how did you go?

**Comment by hansdavid** [comment]
I did not successfully trace any changes on the objects, other than the USN. Neither did I find what process triggers it. 

I did compare the accounts attributes across time whith "get-adobject -proterties *" . I also tried tracing changes using "REPADMIN /showobjmeta" but did not find other changes than the USN,

Enabling auditing on the objects could perhaps show more info, but I do not have permission to do so

Out of approx. 8.000 user accounts there are around 10 accounts showing this behaviour.

I "solved" it by delaying the trigger and I find that solution to be adequate.

The Autosync is a fantastic tool, and I currently have it running in production for one of my customers, as well as in my demo environment.

Thank you for the great efforts Ryan.

**Comment by ryannewington** [comment]
@hansdavid this command might help at least narrow down the attribute that is being changed

```
repadmin /showobjmeta idm-d1ad1-v01 "CN=svc-iammids,OU=ServiceAccounts,OU=Accounts,OU=IdM Managed Objects,DC=fim-dev1,DC=local"
```

You'll get a list of attributes and their 'version' which increments each time the value is changed. If you have any really high numbers on one of those 10 users, that's likely the culprit. Note, this wont show attributes that are not replicated. The example below shows that the 'sn' attribute is at version 3.

```
3048117                   AU\IDM-D1AD1-V01   3048117 2017-11-14 14:22:19    3 sn
```
