### ISSUE TITLE
Default log folder should not be in %ProgramFiles%

### ISSUE THREAD

**Issue by Froosh** [lithnet/miis-autosync#121]
Logs files and similar changeable content shouldn't exist in the %ProgramFiles% hierarchy, as per https://msdn.microsoft.com/en-us/library/ms995853.aspx (Not sure if there is a fresher version of this, but the concept remains).

From https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457(v=vs.85).aspx, it appears **FOLDERID_ProgramData** is the 'proper' location these days.

[Of course, Microsoft doesn't often follow this guidance themselves, but no reason we shouldn't try...]

**Comment by ryannewington** [comment]
@Froosh I agree with this one, but not sure program data is a better place to put them, particularly since this folder is hidden by default. I think I'll leave them at this spot, but the user can always change the location at installation time if needed.
