### ISSUE TITLE
Ability to run a script after an Import run profile has completed

### ISSUE THREAD

**Issue by dminnelli** [lithnet/miis-autosync#122]
Hi Ryan,

  I would like the ability to export the pending exports following an Import run profile for reporting purposes. I was thinking of running a PowerShell script and export the CS Pending Export information using your Synchronization Service PowerShell Module. I could see this being a challenge as you wouldn't want to run Syncs until the script has exited.
  I know the another option would be to export the Import run profile changes to log file, but I like your Sync Service module too much!

  Regards

  David

**Comment by ryannewington** [comment]
Hi David,

Check out the "ExecutionComplete" hook on the controller script. It is called after every run profile, and you can interrogate the results of the run (using the same objects from the PS module)

https://github.com/lithnet/miis-autosync/wiki/Execution-controller-scripts

Does that do what you need?

**Comment by dminnelli** [comment]
Yep, doh, completely missed the actual documentation page of the Execution Controller script. Will have a play. Thanks.
