### ISSUE TITLE
Add next event for date/time triggers to the message log

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/miis-autosync#124]
Nice to see next run time for a scheduled interval in GUI

Don't have to guess / calculate. 

Also the table in the trigger screen could be broken to 

TYPE | RUN PROFILE | TRIGGER INTERVAL | START TIME | NEXT RUN 

Or something on those lines would be nice. But I am thinking that might not be possible with the different types available for triggers. Next Run should still be universal across all trigger types I believe.

**Comment by ryannewington** [comment]
I can't add it to the config screen - it doesn't have access to the live data coming from the service. There is no where to neatly represent it in the execution monitor without a major redesign. All I can really do is add it to the message log to say when the next execution is scheduled for.

**Comment by ryannewington** [comment]
Done in https://github.com/lithnet/miis-autosync/releases/tag/v1.2.6692
