### ISSUE TITLE
Include 'msDS-LastSuccessfulInteractiveLogonTime' as part of AD trigger filter for recent logons

### ISSUE THREAD

**Issue by Froosh** [lithnet/miis-autosync#126]
Actually, there are a few of them related to the '[Provide  information about previous logons to client computers](https://technet.microsoft.com/en-us/library/dd446680(v=ws.10).aspx)' policy on Domain Controllers:
msDS-FailedInteractiveLogonCount
msDS-FailedInteractiveLogonCountAtLastSuccessfulLogon
msDS-LastFailedInteractiveLogonTime
msDS-LastSuccessfulInteractiveLogonTime

With the 'provide information' policy enabled, just about every logon causes the AD trigger to fire, causing non-stop AD syncs.

**Comment by ryannewington** [comment]
Give this guy a go
[autosync.zip](https://github.com/lithnet/miis-autosync/files/1621055/autosync.zip)

**Comment by Froosh** [comment]
Got an error while installing with that:
`Product: Lithnet AutoSync for Microsoft Identity Manager -- Error 1316. The specified account already exists.`

Uninstalled/Reinstalled to work around.

Still getting spurious AD triggers from msDS-LastSuccessfulInteractiveLogonTime changes:
`
2018-01-11 14:03:21.8748| INFO|MIMLab.froosh.net: AD/LDS change detection (DC=MIMLab,DC=froosh,DC=net): Change detected on CN=s-SP-2016-MIMSync,OU=Service Accounts,OU=Management,DC=MIMLab,DC=froosh,DC=net`

Verified that no other data is changing on the claimed trigger account (from Get-ADReplicationAttributeMetadata):
```
LastOriginatingChangeTime attributeName
------------------------- -------------
11/01/2018 2:03:21 PM     msDS-LastSuccessfulInteractiveLogonTime
11/01/2018 11:14:49 AM    lastLogonTimestamp
6/12/2017 4:03:20 PM      msDS-FailedInteractiveLogonCountAtLastSuccessfulLogon
6/12/2017 4:03:03 PM      msDS-LastFailedInteractiveLogonTime
6/12/2017 4:03:03 PM      msDS-FailedInteractiveLogonCount
4/12/2017 2:35:45 PM      whenCreated
4/12/2017 2:35:45 PM      userPrincipalName
4/12/2017 2:35:45 PM      userAccountControl
4/12/2017 2:35:45 PM      unicodePwd
4/12/2017 2:35:45 PM      supplementalCredentials
4/12/2017 2:35:45 PM      sAMAccountType
4/12/2017 2:35:45 PM      sAMAccountName
4/12/2017 2:35:45 PM      pwdLastSet
4/12/2017 2:35:45 PM      primaryGroupID
4/12/2017 2:35:45 PM      objectSid
4/12/2017 2:35:45 PM      objectClass
4/12/2017 2:35:45 PM      objectCategory
4/12/2017 2:35:45 PM      nTSecurityDescriptor
4/12/2017 2:35:45 PM      ntPwdHistory
4/12/2017 2:35:45 PM      name
4/12/2017 2:35:45 PM      msDS-SupportedEncryptionTypes
4/12/2017 2:35:45 PM      logonHours
4/12/2017 2:35:45 PM      lmPwdHistory
4/12/2017 2:35:45 PM      instanceType
4/12/2017 2:35:45 PM      displayName
4/12/2017 2:35:45 PM      dBCSPwd
4/12/2017 2:35:45 PM      countryCode
4/12/2017 2:35:45 PM      codePage
4/12/2017 2:35:45 PM      cn
4/12/2017 2:35:45 PM      accountExpires
```

**Comment by ryannewington** [comment]
That's odd. I've tested on my test domain and its definitely ignoring msDS-LastSuccessfulInteractiveLoginTime.

In fact, in the test I had to force it to skip over lastLogon and lastLoginTimestamp, because they are also set, and cause the trigger to skip that object before it even gets to the new attributes.

Maybe I stuffed up the build. Here's a fresh one just in case.

[autosync.zip](https://github.com/lithnet/miis-autosync/files/1621163/autosync.zip)

**Comment by Froosh** [comment]
It seems the version attached earlier (1:50pm) was from last year, which I hadn't noticed until now either.

Now, the client wont connect to the service:
```
An error occurred with the client registration
System.ArgumentException: A property with the name 'System.ServiceModel.Channels.RemoteEndpointMessageProperty' is not present.
   at System.ServiceModel.Channels.MessageProperties.get_Item(String name)
   at Lithnet.Miiserver.AutoSync.EventService.get_RemoteHost()
   at Lithnet.Miiserver.AutoSync.EventService.Register(Guid managementAgentID)
```

Following along in the log file, and things are looking good there - no unexpected AD triggers.
```
2018-01-11 15:19:43.3303|TRACE|Searching for changes since 2018-01-11T04:19:30.603
2018-01-11 15:19:43.3458|TRACE|Found 0 changes
```

**Comment by ryannewington** [comment]
[autosync.zip](https://github.com/lithnet/miis-autosync/files/1621249/autosync.zip)

Sorry, have been working on the remote management and had some not-quite-finished code active there.

Third time lucky!

**Comment by Froosh** [comment]
Huzzah! 😀

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.2.6692
