### ISSUE TITLE
Removing a trigger does not register as a change in the UI

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/miis-autosync#128]
Tested on latest v1.1.6582.24440.

After deleteing trigger it doesn't think any changes have been made. Thus it seems to be gone from GUI but not removed from config. And a reload of config gets the trigger back.

**Comment by ryannewington** [comment]
It does make the change, it just isn't updating the version number, so the change is not being 'seen'. If you change another value and save it will work.

**Comment by khandelwalpiyush** [comment]
No it actually doesn't.. I had to go into config and delete the XML blob of the trigger which I wanted to delete.. Unless that is what you meant

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.2.6692
