### ISSUE TITLE
Stopping a MA Run

### ISSUE THREAD

**Issue by Manjunath-hk1** [lithnet/miis-autosync#139]
If we stop the MA without cancelling the running profile, the message shows "unmanaged run profile in progress". At this point we don't have control to cancel the running profile. can we have the mechanism to cancel the run profile.

**Comment by ryannewington** [comment]
@Manjunath-hk1 I can't seem to reproduce this one. Can you detail the steps I can take to replicate this problem please?

**Comment by Manjunath-hk1** [comment]
Hi Ryan,

Thanks for looking into this.
I have tried again and couldn't reproduce the behavior in couple of ways.The tool works as expected.
Apologies for inconvenience.

Thank You,
Manju
