### ISSUE TITLE
Alert mails with same details not being triggered.

### ISSUE THREAD

**Issue by Manjunath-hk1** [lithnet/miis-autosync#140]
If the MA creates the same error day to day which might be an important  alert, it looks like the alerts are not being sent by mail considering they are same.

It is tricky to distinguish the subsequent errors with same message.

example : no start ma : Which looks same all the time.

**Comment by ryannewington** [comment]
Under settings->mail you can set error reports to "send always". The default is "only send the first time a specific error occurs".
