### ISSUE TITLE
TypeInitializationException and InvalidCastException thrown when calling LithnetRMA from an execution controller

### ISSUE THREAD

**Issue by johnyukloud** [lithnet/miis-autosync#141]
When I invoke Lithnet Resource Management PS from MA executor, it would fail on 

**Set-ResourceManagementClient -BaseAddress "http://localhost:5725";**

there is error in the application eventlog about System.TypeInitializationException: The type initializer for 'Lithnet.ResourceManagement.Client.ResourceManagementClient' threw an exception. 

Seems it is not able to access the configure file when executed from the MA executor.

**The code I executed as follow:**

```
function ExecutionComplete
{
	param([Lithnet.Miiserver.Client.RunDetails]$lastRunDetails)
        
	# If the run was an import an a change was made, create the MACD report
	foreach ($step in $lastRunDetails.StepDetails)
	{
		if ($step.StepDefinition.Type -eq 'FullImport'){		
			Set-ResourceManagementClient -BaseAddress "http://localhost:5725";
			
			$terminatedPortalUsers = Search-Resources -Xpath "/Person[(EmployeeEndDate > op:subtract-dayTimeDuration-from-dateTime(fn:current-dateTime(), xs:dayTimeDuration('P1D'))) and (EmployeeEndDate < fn:current-dateTime())]" -AttributesToGet @("AccountName","EmployeeEndDate","EmployeeID")

			$terminatedPortalUsers | Export-Csv "C:\temp\test1.txt" -notype
			
			$psons = Get-MVObject -ObjectType person
			$psons | Export-Csv "C:\temp\test2.txt" -notype
		}
	}
}
```

**The error in the eventlog as below:**

> Ascender SQL MA: ExecutionComplete handler threw an exception
> System.ApplicationException: The PowerShell script encountered an error
> at ExecutionComplete, <No file>: line 20
> System.TypeInitializationException: The type initializer for 'Lithnet.ResourceManagement.Client.ResourceManagementClient' threw an exception. ---> System.InvalidCastException: [A]Lithnet.ResourceManagement.Client.ClientConfigurationSection cannot be cast to [B]Lithnet.ResourceManagement.Client.ClientConfigurationSection. Type A originates from 'Lithnet.ResourceManagement.Client, Version=1.0.6297.14599, Culture=neutral, PublicKeyToken=bd0636700c1e2538' in the context 'LoadNeither' in a byte array. Type B originates from 'Lithnet.ResourceManagement.Client, Version=1.0.6435.24336, Culture=neutral, PublicKeyToken=bd0636700c1e2538' in the context 'LoadFrom' at location 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\LithnetRMA\Lithnet.ResourceManagement.Client.dll'.
>    at Lithnet.ResourceManagement.Client.ClientConfigurationSection.GetConfiguration()
>    at Lithnet.ResourceManagement.Client.ResourceManagementClient..cctor()
> 
> 

what is the proper way to execute Lithnet Resource Management PS from MA executor from the Executor MA?

I have tried to wrap around the call inside a script block, it works but the Get-MVObject would fail, it would return 

> The Synchronization Service Manager service has stopped.

when the Synchronization Service Manager service is actually running.

**Comment by ryannewington** [comment]
@johnyukloud this is definitely a bug, but a complex one to solve. I'll look to resolve this in v2. In the mean time, the workaround would be to launch a new instance of PowerShell to run the fim service query such as shown in this example https://stackoverflow.com/questions/23237473/powershell-launch-script-in-new-instance

You seem to be referencing another issue with Get-MVObject. That is from a different PowerShell module. Can you provide more information about the context of the issue you are having there?

**Comment by ryannewington** [comment]
@johnyukloud I'm working on the fix for this, but I've got a cleaner workaround you can use in the mean time. Edit the Lithnet.Miiserver.AutoSync.exe.config file and remove the following two lines

```xml
<section name="lithnetResourceManagementClient" type="Lithnet.ResourceManagement.Client.ClientConfigurationSection, Lithnet.ResourceManagement.Client"/>
```
and
```xml
<lithnetResourceManagementClient resourceManagementServiceBaseAddress="http://localhost:5725"/>
```

This will prevent the error you are seeing. These lines are not needed for AutoSync or the PowerShell module to work.

**Comment by ryannewington** [comment]
@johnyukloud i'm marking this issue as done. You can apply the workaround above, or install the latest version of LithnetRMA from https://github.com/lithnet/resourcemanagement-powershell/releases/tag/v1.0.6623 

If you are still having issues with Get-MVObject, please open a new issue, and we work on that one separately, as it is unrelated to what is going on here.

**Comment by johnyukloud** [comment]
Great! Thanks Ryan
