### ISSUE TITLE
Import/Export deletes threshold

### ISSUE THREAD

**Issue by Identitry** [lithnet/miis-autosync#154]
Hi Ryan!
Maybe there's a recommended way of doing this using Powershell Trigger but it would be great if it then could be documented in the wiki...

However, in my old sync scripts I usually have a 5% threshold for import deletes/export deletes, if excedded, the script is stopped and an error email is sent. This functionality would be great to have in the UI for each MA in AutoSync.

//Henrik

**Comment by ryannewington** [comment]
Hey @Identitry 

You're after the execution controller script. Here AutoSync gives you the opportunity to interrogate the connector space after a run profile has executed. 

Here's a bit more detail along with an example of how to do what you are after!

https://github.com/lithnet/miis-autosync/wiki/Execution-controller-scripts

**Comment by ryannewington** [comment]
Hi @Identitry,

Feel free to open this again if you need more help

ryan
