### ISSUE TITLE
AutoSync uses an ephemeral port

### ISSUE THREAD

**Issue by s881628** [lithnet/miis-autosync#155]
AutoSync currently uses port 54338, which is in the ephemeral range.  This causes an intermittent issue whereby the AutoSync service fails to start if if something else is using the port.  The port selected should be outside of the 49152 - 65535 range

> 2018-09-10 08:13:46.3965|ERROR|Unable to start serviceSystem.ServiceModel.AddressAlreadyInUseException: There is already a listener on IP endpoint [::]:54338. This could happen if there is another application already listening on this endpoint or if you have multiple service endpoints in your service host with the same IP endpoint but with incompatible binding configurations. ---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by ryannewington** [comment]
Default port is now `41338`
However this can be overridden with a DWORD valued called `NetTcpBindPort` in `HLKMSystem\CurrentControlSet\Services\autosync\Parameters` for the server side and a DWORD called `AutoSyncServerPort` in `HKCU\Software\Lithnet\AutoSync` on the client side
