### ISSUE TITLE
Scheduled interval trigger stops firing after the controller has been manually stopped and restarted

### ISSUE THREAD

**Issue by mrmueller** [lithnet/miis-autosync#158]
So this time, the triggers on some MA's just dont seem to fire. There is no obvious reason available in the execution monitor.

Edit: Reviewing the logs i realised that the controlles has been stopped and started again few minutes later. It looks like the triggers got registered, fired once but then never again.

Note: The trigger should fire every 30 minutes. Still, the last run was over 13 hours ago now.
![autosync5](https://user-images.githubusercontent.com/9515311/49991529-afcb4b00-ff81-11e8-8a60-bb1dd0fa3679.png)
![autosync4](https://user-images.githubusercontent.com/9515311/49991533-b2c63b80-ff81-11e8-8867-221c729220fb.png)

@ryannewington i will provide the logs for this case by email. Hope that is ok.

**Comment by jakolars** [comment]
This is the same issue we are experiencing, so if needed i also can try to generate some logs.

**Comment by ryannewington** [comment]
@jakolars I agree I think this is the same issue you are facing. Are you able to email me to following ryan@lithnet.io

- Logs dating back to the startup of the service
- The name of the MA and the name of the trigger
- The time when the trigger last fired
- The time when the trigger should have fired according to the schedule

Were the controllers stopped and started by a user at any time before they stopped responding, or has it been left alone the whole time?

@mrmueller I'm still analyzing the data you sent through.

**Comment by ryannewington** [comment]
Never mind, found the issue

**Comment by ryannewington** [comment]
@mrmueller @jakolars New build available with this fix 

https://github.com/lithnet/miis-autosync/releases/tag/v1.2.6927

**Comment by mrmueller** [comment]
@ryannewington Thanks!
