### ISSUE TITLE
AutoSync service fails to start: Must be FIM Sync Admins or FIM Sync Operators

### ISSUE THREAD

**Issue by microfoundry** [lithnet/miis-autosync#162]
Just patched a MIM Sync box to 4.5.286.0 and AutoSync 1.2.6995.24204 and the AutoSync service fails to start. I'm receiving the "Must be FIM Sync Admins or FIM Sync Operators". I've verified the account is member of FIM Sync Operators and can use the account to manually execute run cycles within MIISClient. Additionally, putting the account in FIM Sync Admins DOES allow the AutoSync service to start...

**Comment by ryannewington** [comment]
Hi @microfoundry. That's a documentation bug. Autosync does require FIM Sync Admin rights to run. An earlier version with less features used to allow FIM Sync operators. Apologies for the confusion.

**Comment by microfoundry** [comment]
Hey Ryan - thank you for the clarification. No worries, just want to make sure it wasn't me...

Keep up the awesome work. I really appreciate the tools you've created.

-Terry
