### ISSUE TITLE
No way to remove management agents

### ISSUE THREAD

**Issue by JamieB226-westrock** [lithnet/miis-autosync#168]
We have several management agents that have been removed from our MIM config, but they still show up in AutoSync.  I don't see any way to delete them or otherwise remove them from the list.

**Comment by ryannewington** [comment]
Hi Jamie,

When the management agent is removed from MIM, it should appear in AutoSync as 'missing'. You may need to restart autosync for it to detect the missing management agent. Once it does, you'll have the option to right-click and remove

![image](https://user-images.githubusercontent.com/17229877/69759531-7271c480-11b6-11ea-94ee-a1ac6b8d941e.png)

**Comment by JamieB226-westrock** [comment]
Mine just show unconfigured in italics when I remove them.  Let me make sure I’m on the most current version.

—
Jamie Booth
Windows Core Architect
WestRock
jamie.booth@westrock.com
________________________________

**Comment by ryannewington** [comment]
What happens if you modify config and save it?

**Comment by JamieB226-westrock** [comment]
I was a version or so back.  Latest version works as you described.
