### ISSUE TITLE
Trojan detected in AutoSync installer

### ISSUE THREAD

**Issue by tomazmla** [lithnet/miis-autosync#170]
Hi,

running AutoSync.msi from version v1.2.6692 on is blocked by Kaspersky Endpoint Security 11.x detecting [Trojan.MSIL.Cryptos](https://threats.kaspersky.com/en/threat/Trojan.MSIL.Cryptos/) trojan. Any solution to this?

Thanks,
Tomaz

**Comment by ryannewington** [comment]
Hi Tomaz,

Thanks for reporting. I believe this is a false positive in their heuristics engine, and I'm no longer getting a positive result when testing the file against https://opentip.kaspersky.com/.

Can you confirm if you are still seeing this problem?

Ryan

**Comment by tomazmla** [comment]
Hi Ryan,

you are correct. Also got the confirmation from Kaspersky that is the case. 

Thanks,
Tomaz
