### ISSUE TITLE
Invalid URL on Wiki page "Installing AutoSync"

### ISSUE THREAD

**Issue by bisk-e** [lithnet/miis-autosync#172]
Step 4 has an invalid link for the "Configuration" URL.
https://github.com/lithnet/miis-autosync/wiki/Installing-AutoSync#step-4-configure-the-service

It is pointing to https://github.com/lithnet/miis-autosync/wiki/configuration which doesnt exist. 
It should point to https://github.com/lithnet/miis-autosync/wiki/Configuring-the-AutoSync-service.

**Comment by ryannewington** [comment]
Thank you! link has been updated.
