### ISSUE TITLE
Setup should allow for gMSA principal to be used for the service

### ISSUE THREAD

**Issue by Niehweune** [lithnet/miis-autosync#174]
Setup currently doesn't support using a Group Managed Service Account for the Autosync service. When a gMSA is specified, setup:
- requires the password fields to be filled in, which isn't possible for gMSA's
- when adding the user to the group is checked, setup throws an error stating the objecttype computeraccount isn't supported when adding to a group (effectively breaking off setup and rolling back)

As a workaround, it does work when:
- specifying a bogus password when setup asks for it
- unchecking the 'add user to group' mark (and doing this ourselves if needed).

**Comment by ryannewington** [comment]
Thanks for reporting this. Fixed in the latest release 

https://github.com/lithnet/miis-autosync/releases/tag/v1.2.8002
