### ISSUE TITLE
Not detecting that execution has completed

### ISSUE THREAD

**Issue by mrmueller** [lithnet/miis-autosync#175]
Hi Ryan, thanks again for this great tool.

For some reason, it has stopped detecting when one of my MA's completes. 
In Autosync, State just remains as "Running", even though the State on the MA in MIM is idle again.
Autosync does not seem to be able to recover from this, even after many hours.

The MA is called AAD_Mobile, it is a psma by Soren.
Exporting results in errors which are to be expected.
In the example here, 0 exported objects complete successfully. However, even if some complete successfully, the problem is the same.

This is what the GUI looks like
![image](https://user-images.githubusercontent.com/9515311/153045859-8f85c400-5db6-4e77-8479-2bd8363be7ce.png)

And here is a trace from starting the service and then starting only the AAD_Mobile controller.
[autosync.log](https://github.com/lithnet/miis-autosync/files/8026302/autosync.log)

I'm running Autosync version 1.2.8002.27749 and MIM version 4.6.531.0

Any idea what i could do?
Let me know if I can provide some additional information.

Thanks
Martin

**Comment by ryannewington** [comment]
@mrmueller what status did that last run finish with in the sync engine?

**Comment by mrmueller** [comment]
@ryannewington it finishes with "completed-export-errors"

**Comment by ryannewington** [comment]
Hmm. That doesn't make much sense. When it's next in that state, can you please go to task manager and right click on the autosync server process exe and select create memory dump. Share the resulting file via onedrive to support@lithnet.io. We'll debug from our side and see what it thinks it's waiting for.

**Comment by mrmueller** [comment]
This is the latest run. Sending dump shortly.
![image](https://user-images.githubusercontent.com/9515311/153191876-6d25e27d-eddb-465a-ae6b-c78370a74ae7.png)

**Comment by mrmueller** [comment]
Thanks for the help you provided by email Ryan!
Really appreciate you doing this even though it was clear early on that this issue was not related to autosync.

**Solution for people finding this later:**
Autosync is calling the "Execute" WMI method on the management agent, and that method (usually) returns once the run is finished. It was not returning here.

Problem was that my export powershell script was not handling one exception properly.

try{
                $ErrorActionPreference = "Stop"
                New-MgUserAuthenticationPhoneMethod -UserId $userPrincipalName -PhoneNumber $primaryPhone -PhoneType "mobile" -SmsSignInState "ready"                
      }catch{
                $obj = @{}
                $obj.Add("[Identifier]",$Identifier) 
                $obj.Add("[ErrorName]",$($_.Exception.Message))
                $obj.Add("[ErrorDetail]",$($primaryPhone))
                $obj
      } 

The Powershell Cmdlet New-MgUserAuthenticationPhoneMethod was throwing an exception which was not caught as I would have expected
I had to add $ErrorActionPreference = "Stop" before the command because New-MgUserAuthenticationPhoneMethod does not support -ErrorAction

Now that the exception is caught, MIM seems to complete the WMI call as expected and Autosync can continue without issues.
