### ISSUE TITLE
AutoSync service running with GMSA and MIM MA change detection?

### ISSUE THREAD

**Issue by microfoundry** [lithnet/miis-autosync#177]
Greetings - what's the trick to allow GMSA to work with change detection? I have the GMSAs synced into MIM as a custom object but the change detection is throwing a "exception "Identity is not found" error...

TIA,

Terry

**Comment by ryannewington** [comment]
Hi Terry,

Unfortunately, the MIM service only recognizes logins from the `person` object class. You might have some luck hacking the GMSA ObjectSid into a manually created `person` object in the MIM service - but I haven't tried this personally.

**Comment by sean-m** [comment]
I can confirm that syncing GMSA's into the MIM Service as Person objects does work and change detection functions as you'd expect.

**Comment by ryannewington** [comment]
Awesome! Good to know and glad its working!
