### ISSUE TITLE
Installer Downloads No Longer Available

### ISSUE THREAD

**Issue by mpunderw** [lithnet/miis-autosync#182]
There are no releases available for download.

**Comment by ryannewington** [comment]
@mpunderw i can see them all there?

This is the latest 

https://github.com/lithnet/miis-autosync/releases/tag/v1.2.8002

**Comment by mpunderw** [comment]
That's crazy, when I followed the link from here in github and from the lithnet.io website the list of releases was blank. I can now see them. I even tried on multiple computers. I can see them now. Thanks for your help.

**Comment by mpunderw** [comment]
closing
