### ISSUE TITLE
How to exclude a Repeating interval trigger to run certain times but still be able to run a Scheduled interval trigger during that times

### ISSUE THREAD

**Issue by mwwessie** [lithnet/miis-autosync#183]
We have 19 MAs with 130000 objects in the MV, which the FIFS takes quite a time to complete. We have configured a Repeating interval trigger for every MA to run a DI every 15 minutes and have configured Scheduled interval Triggers to run on certain times to run a FIFS. We have also configured the Scheduled interval trigger to run exclusively.
![image](https://github.com/lithnet/miis-autosync/assets/27192287/7e186154-5d5e-4ec3-97e2-85b7142d180e)

The Repeating interval trigger still runs during between the Scheduled interval triggers.
![image](https://github.com/lithnet/miis-autosync/assets/27192287/e97d5483-796f-46e5-b776-ec28c01c75b8)

I'm using the PowerShell script with the function ShouldExecute to exclude all runs between 00:00 and 02:00 for each MA:

```powershell
# This function is called by the MA executor before a run profile is executed. Return $false to prevent the run profile from being executed
# Returning $true or nothing will allow the run profile to execute
function ShouldExecute
{
	param([string]$runProfileName)

    # Exclusion window start time
    $exclusionStartTime = "00:00"

    # Exclusion window end time
    $exclusionEndTime = "02:00"    

    # Current date/time
    $now = Get-Date

    #if it is exclusion time, don't run this MA
    if ($now -ge (Get-Date $exclusionStartTime) -and $now -lt (Get-Date $exclusionEndTime))
    {
        # Current time is withing patching window, do not start this run profile
        return $false
    }

	return $true;
}
``` 
I've configured this in the Advanced section of each MA:
![image](https://github.com/lithnet/miis-autosync/assets/27192287/86632c57-f4f7-4e44-9265-6863f8d6210e)

The Repeating interval trigger runs still occur between the Scheduled interval runs:
![image](https://github.com/lithnet/miis-autosync/assets/27192287/cc4ec5f1-bf01-4be9-9ed6-26cf434bfc4a)

Is there a way to exclude the Repeating interval trigger not to run between certain times and then to be able to run the Scheduled interval Triggers between that times?

**Comment by ryannewington** [comment]
I think you are on the right track but you start and end times in your PS script don't have a date, only a time. So is suspect .net is interpreting them as 1/1/1600 02:00 and 0:00 and therefore not matching your logic criteria.

Suggest that it may be simpler to check that [System.DateTime]::Now.Hour is equal to or greater than 0 and less than or equal to 2

**Comment by mwwessie** [comment]
Thanks you Ryan, I've updated the PS Function as follow:
```powershell
# This function is called by the MA executor before a run profile is executed. Return $false to prevent the run profile from being executed
# Returning $true or nothing will allow the run profile to execute
function ShouldExecute
{
	param([string]$runProfileName)

    # Exclusion window start time
    $exclusionStartTime = "0"

    # Exclusion window end time
    $exclusionEndTime = "2"    

    # Current date/time
    $now = [System.DateTime]::Now.Hour

    #if it is exclusion time, don't run this MA
    if ($now -ge ($exclusionStartTime) -and $now -lt ($exclusionEndTime))
    {
        # Current time is withing patching window, do not start this run profile
        return $false
    }

	return $true;
}
``` 

I've tested it in the ise and it give me desired outcome to exclude all runs during 00:00 and 02:00, how do I only exclude the Repeating interval trigger to only run between certain time slots. It would be nice to have a selection in the GUI for exclusion times for the Repeating interval triggers.

**Comment by ryannewington** [comment]
I think this is the only solution I can think without major work to the trigger mechanism itself.

**Comment by mwwessie** [comment]
Thanks
________________________________
