### ISSUE TITLE
Correlation between Execution History and Message log window

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/miis-autosync#68]
Don't know if possible due to free text field, but if we can - when we click on a execution history , it scrolls to the message log for that timestamp

**Comment by ryannewington** [comment]
Help me understand the thinking behind this one. What is the autosync log going to show you that you don't already know from the execution history?

**Comment by khandelwalpiyush** [comment]
No.. What I am trying to say is that when you click on one of the results in "Execution History", if its possible to scroll the "message log" to that event automatically.

**Comment by ryannewington** [comment]
I know what you want it to do, i'm trying to understand why

**Comment by khandelwalpiyush** [comment]
No particular reason.. if there is an error, you can click on it and will scroll to the log point.. good for easy location of logs for debugging if needed..

**Comment by ryannewington** [comment]
That's what i'm saying though. If a run profile fails in the sync engine and say returns 'no-start-ma' you are only going to see "MA returned no-start-ma" in the main log at the time the error happened. I don't think the main log is going to tell you anything helpful at all
