### ISSUE TITLE
Ability to get notification if the Profile has run longer than expected

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/miis-autosync#7]
In quite a few occasions we have seen that few run profiles in some MA are hung and that the profile is still running. This leads to a queue build up and virtually stalling operations in the environment. 

Although not a autosync issue, it would be nice to enable a feature whereby which we can mention the expected runtime of a run profile for an MA and if it has taken longer then that, we are sent an email notification of the same so that we can check it and potentially stop a backlog in production environment.

**Comment by ryannewington** [comment]
This would be a bit tricky with the locking mechanisms in play. I'm going to close this one with a wontfix.
