### ISSUE TITLE
Remote Management - GUI won't refresh unless you click on it

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/miis-autosync#92]
If you using this for monitoring on a black box or something which is being viewed remotly.. unless someone goes and click on the GUI (if changes were made via local GUI or vice versa), the GUI won't refresh indicating the change. Like Execution Monitor is stopped but the button hasn't changed status. 

Not sure if auto refresh can be put it which refreshes the GUI as well.

**Comment by khandelwalpiyush** [comment]
This is not related just to remote-access. This is also the case for local GUI.. 

An Example: 
Click on "Stop All" - it will not refresh the GUI unless you click anywhere else which will then enable the "start all" button

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.1.6500
