### ISSUE TITLE
Create Set and MPR fails if the service account username is not in domain\username format

### ISSUE THREAD

**Issue by Froosh** [lithnet/miis-autosync#98]
No other information is available so far. No eventlog messages, no success/failed requests in FIM Service, nothing in the log file, no user/set/mpr created.

![image](https://user-images.githubusercontent.com/1386517/30622113-e2ef985c-9df2-11e7-880f-6c95913ce0ac.png)

**Comment by ryannewington** [comment]
That's rather unhelpful. Could you download dbgview from sysinternals, run it, and reproduce the error? It should have the stack trace in there. If you can post that back, that would be great!

**Comment by Froosh** [comment]
Heh, I was in the process of doing that 👍 

```
[4300] Person svc-MIMAutoSync@MIMLab.froosh.net was not found. Creating 
[4300] System.IndexOutOfRangeException: Index was outside the bounds of the array. 
[4300]    at Lithnet.Miiserver.AutoSync.FimServicePendingImportTrigger.CreateMpr(String hostname, NetworkCredential creds, String accountName, String setName, String mprName) 
[4300]    at Lithnet.Miiserver.AutoSync.UI.ViewModels.FimServicePendingImportTriggerViewModel.CreateMpr() 
```

I get the same result whether I enter credentials or leave them empty.

**Comment by ryannewington** [comment]
Ah, it's assuming a domain\username, not username@fqdn. There's no slash so its unceremoniously dying.

A workaround for you is to change the `ObjectName` parameter in the following reg key to be domain\username format. I'll take this as a bug and fix for the next release.

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\autosync`

**Comment by Froosh** [comment]
Done. Yep, works perfectly now, and handily added descriptions to the set/mpr I had created manually.

Awesome work, thanks! 😁

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.1.6500
