### ISSUE TITLE
Timestamps in log file are not ISO8601/RFC3339 or similar

### ISSUE THREAD

**Issue by Froosh** [lithnet/miis-autosync#99]
Can we agree that US date formats don't sort well?

**Comment by ryannewington** [comment]
Hey @froosh!

Yuck! But it should be using what ever the system's short date format is. What the default system locale set to?

**Comment by Froosh** [comment]
Yeah, I initially had a locale setting issue :( uninstalled, removed service profile, confirmed locale settings, reinstalled and am now getting regional format.

Still a fan of the ISO8061/RFC3339 formats :)

**Comment by ryannewington** [comment]
Ill keep this issue around as an enhancement to allow a customisable date format

**Comment by ryannewington** [comment]
I've swapped out the logging engine to use nlog, which does this by default. It will be in the next build.

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.1.6500
